Resources:
  SimpleEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t3.micro
      ImageId: ami-00c8ac9147e19828e  # AMI ID for your region
      Tags:
        - Key: Name
          Value: MySimpleInstance
